# Generated by Django 2.2.9 on 2020-10-13 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('catid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategories',
            fields=[
                ('subcatid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('catid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='get_city_deals_api_app.Categories')),
            ],
        ),
    ]
